name: build and deploy

on:
   workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sit
          - prod
env:
    image_name: hello-world

concurrency:
    group: deploy-${{ github.ref_name }}
    cancel-in-progress: true
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: checkout code
          uses: ./actions
          with:
             image_name: ${{ env.image_name }}

        #- name: docker setup
        #  uses: docker/setup-buildx-action@v3 

        #- name: docker pull ${{ env.image_name }}
        # run: docker pull $image_name
        
    deploy:
        needs: first_job
        
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment }}
        steps:

        - name: docker build
          run: docker run  ${{ inputs.image_name }}






