name: build and deploy

on:
    push:
        branches:
            - main
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: docker setup
          uses: docker/setup-buildx-action@v3 

        - name: docker build
          run: docker pull hello-world
        
    deploy:
        needs: first_job
        runs-on: ubuntu-latest
        steps:

        - name: docker build
          run: docker run  hello-world






