name: build and deploy

on:
    push:
        branch:
            main
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: welcome msg
          run:  echo "my first job"

        - name: list files
          run: ls 






