name: build and deploy

on:
    push:
        branches:
            - main

    workflow_dispatch:
env:
    image_name: hello-world
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: docker setup
          uses: docker/setup-buildx-action@v3 

        - name: docker pull ${{ env.image_name }}
          run: docker pull $image_name
        
    deploy:
        needs: first_job
        runs-on: ubuntu-latest
        steps:

        - name: docker build
          run: docker run  $image_name






