name: build and deploy

on:
    push:
        branch:
            main
jobs:
    first job:
        runner-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: welcome msg
          run:  ech0 "my first job"

        - name: list files
          run: ls 






