name: build and deploy

on:
    push:
        branch:
            main
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: welcome msg
          run:  echo "my first job"

        - name: docker build
          run: docker build -t hello-world
        
    deploy:
        runs-on: ubuntu-latest
        steps:

        - name: docker build
          run: docker run -d -p 8080:8080 hello-world






